### ISSUE TITLE
Evaluation company in a Sandbox

### ISSUE THREAD

**Issue by andywingate** [StefanMaron/BusinessCentral.Sentinel#2]
Hi Stefan,

How does sentinel determine the environment is a Prod instance?  

In this example I've deployed the app to a Sandbox and did the analysis:

![image](https://github.com/user-attachments/assets/7feb0448-72dd-4d73-9618-ccc04087462f)

Its not clear from the line if the agent is referring to the Cronus UK Ltd in the current environment or the company of the same name in the environment called Production:

![image](https://github.com/user-attachments/assets/dc7241b5-d5e8-4f8e-ad0f-8d48102fd603)

Cheers
Andy

**Comment by StefanMaron** [comment]
That is the message, need to fix that. 
I also need to spend some time for a better description of the rules, I did not want to do that on stream.

The rule does do the analysis within the current environment, and the rule is an `info` in sandbox and a `warning` in production.

The way it identifies companies is by the `Evaluation` boolean on the company list, if you search for `companies` you should find that list.

**Comment by StefanMaron** [comment]
I changed the description so its not as confusing
