### ISSUE TITLE
The record is already open.

### ISSUE THREAD

**Issue by MortenRa** [StefanMaron/BusinessCentral.Sentinel#5]
Not sure if I need to setup anything 

Getting this error when running Analysis

Error message: 
**The record is already open.**

AL call stack: 
ShopifyConnectorInstalledSESTM(CodeUnit 71180283).HasShopsInAnyCompany line 11 - BusinessCentral.Sentinel by Stefan Maron Consulting
ShopifyConnectorInstalledSESTM(CodeUnit 71180283).CreateAlerts line 12 - BusinessCentral.Sentinel by Stefan Maron Consulting
AlertSESTM(Table 71180275).FindNewAlerts line 12 - BusinessCentral.Sentinel by Stefan Maron Consulting
AlertListSESTM(Page 71180275)."RunAnalysis - OnAction"(Trigger) line 2 - BusinessCentral.Sentinel by Stefan Maron Consulting

and when running a full-rerun I get this Error

If requesting support, please provide the following details to help troubleshooting:

Error message: 
**The number sequence 'BCSentinelSESTMAlertId' does not exist.**

AL call stack: 
AlertSESTM(Table 71180275).ClearAllAlerts line 3 - BusinessCentral.Sentinel by Stefan Maron Consulting
AlertSESTM(Table 71180275).FullRerun line 2 - BusinessCentral.Sentinel by Stefan Maron Consulting
AlertListSESTM(Page 71180275)."FullReRun - OnAction"(Trigger) line 2 - BusinessCentral.Sentinel by Stefan Maron Consulting

**Comment by MortenRa** [comment]
btw using version: 1.2.15.0

**Comment by StefanMaron** [comment]
Thanks for reporting! Should have seen that.
Will push the new version asap :)

**Comment by StefanMaron** [comment]
@MortenRa Let me know if the issue still persists on version 1.3.17.0

**Comment by MortenRa** [comment]
@StefanMaron Works in version 1.3.17.0
