### ISSUE TITLE
[SE-000007] Extension "" is installed but unused

### ISSUE THREAD

**Issue by TheDoubleH** [StefanMaron/BusinessCentral.Sentinel#7]
I have five lines that does not show the extension name. Makes it hard to remove...

The only non-Microsoft app installed, if Sentinel.

![image](https://github.com/user-attachments/assets/ed9df226-6305-4e0e-8d26-7e758aa94476)

**Comment by StefanMaron** [comment]
That's not ideal, let me have a look 😅

**Comment by StefanMaron** [comment]
New version deployed to AppSource.
